# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.9"

  jobs:
    pre_install:
      # Install MkDocs and its plugins
      - pip install "mkdocs>=1.6.1"
      - pip install "mkdocs-material>=9.6.11"
      - pip install "mkdocs-material-extensions>=1.3.1"
      - pip install "mkdocs-mermaid2-plugin>=1.2.1"
      - pip install "mkdocs-autorefs>=1.4.1"
      - pip install "mkdocs-get-deps>=0.2.0"
      - pip install "mkdocstrings>=0.29.1"
      - pip install "mkdocstrings-python>=0.29.1"

  commands:
    # Build the MkDocs documentation
    - mkdocs build
    # Ensure the output directory exists
    - mkdir --parents $READTHEDOCS_OUTPUT/html
    # Move the built site to the Read the Docs output directory
    - mv site/* $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml