# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    # Install dependencies
    - pip install -e ".[docs]"
    # Build the MkDocs documentation
    - mkdocs build


# Use MkDocs to build the documentation
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

search:
  ranking:
    # Push API docs in the /api directory down the ranking
    api/*: -5
