# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  commands:
    # Install dependencies
    - pip install -e ".[docs]"
    # Build the MkDocs documentation
    - mkdocs build --strict
    # Run a link checker on the built site
    - linkchecker site --check-extern --no-warnings --ignore=404.html --ignore-url=127.0.0.1
    # Move the built site to the Read the Docs output directory
    - mkdir --parents $READTHEDOCS_OUTPUT/html
    - mv site/* $READTHEDOCS_OUTPUT/html

# Use MkDocs to build the documentation
mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

search:
  ranking:
    # Push API docs in the /api directory down the ranking
    api/*: -5