site_name: ""
site_url: https://docs.kedro.org

theme:
  name: material
  palette:
     # Palette toggle for light mode
    - scheme: light
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: en
  font:
    text: Inter
    code: Inter Regular
  favicon: "https://kedro.org/images/favicon.ico"
  logo: assets/kedro-horizontal-color-on-light.svg


  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.annotate
    - content.code.highlight

plugins:
  - search
  - autorefs
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: true
            show_source: false #currently doesn't show source at correct level, and not for pydantic models
            docstring_style: google
            merge_init_into_class: true
            docstring_section_style: list
            separate_signature: true
            show_root_heading: true
            docstring_options:
              ignore_init_summary: true
              warn_unknown_params: false
              returns_named_value: false
          paths: [src]

extra_css:
  - stylesheets/colors.css
  - stylesheets/globals.css
  - stylesheets/themes.css


nav:
  - Home: pages/index.md
  - Kedro:
      - LEARN ABOUT KEDRO:
          - Introduction: pages/introduction/index.md
          - First steps: pages/get_started/index.md
          - Learn Kedro with hands-on video: pages/course/index.md
      - TUTORIAL AND BASIC USAGE:
          - Tutorial: pages/tutorial/spaceflights_tutorial.md
          - Visualisation with Kedro-Viz: pages/visualisation/index.md
          - Kedro for notebook users: pages/notebooks_and_ipython/index.md
          - FAQs and resources: pages/resources/index.md
      - KEDRO PROJECTS:
          - Customise a new project: pages/starters/index.md
          - Configuration: pages/configuration/index.md
          - Data catalog: pages/data/index.md
          - Nodes and Pipelines: pages/nodes_and_pipelines/index.md
          - Anonymous Telemetry: pages/configuration/telemetry.md
      - INTEGRATIONS:
          - PySpark integration: pages/integrations/pyspark_integration.md
          - How to add MLflow to your Kedro workflow: pages/integrations/mlflow.md
          - Data and pipeline versioning with Kedro and DVC: pages/integrations/kedro_dvc_versioning.md
          - Data versioning with Delta Lake: pages/integrations/deltalake_versioning.md
          - Data versioning with Iceberg: pages/integrations/iceberg_versioning.md
      - DEVELOPMENT:
          - Set up Visual Studio Code: pages/development/set_up_vscode.md
          - Set up PyCharm: pages/development/set_up_pycharm.md
          - Debugging: pages/development/debugging.md
          - Automated Testing: pages/development/automated_testing.md
          - Code formatting and linting: pages/development/linting.md
      - ADVANCED USAGE:
          - Project setup: pages/kedro_project_setup/index.md
          - Extend Kedro: pages/extend_kedro/index.md
          - Hooks: pages/hooks/index.md
          - Logging: pages/logging/index.md
      - DEPLOYMENT:
          - Introduction: pages/deployment/index.md
          - Nodes grouping: pages/deployment/nodes_grouping.md
          - Single-machine deployment: pages/deployment/single_machine.md
          - Distributed deployment: pages/deployment/distributed.md
          - Airflow: pages/deployment/airflow.md
          - Amazon SageMaker: pages/deployment/amazon_sagemaker.md
          - Amazon EMR Serverless: pages/deployment/amazon_emr_serverless.md
          - AWS Step Functions: pages/deployment/aws_step_functions.md
          - Azure: pages/deployment/azure.md
          - Dask: pages/deployment/dask.md
          - Databricks: pages/deployment/databricks/index.md
          - Kubeflow: pages/deployment/kubeflow.md
          - Prefect: pages/deployment/prefect.md
          - Vertex AI: pages/deployment/vertexai.md
          - Argo Workflow (outdated documentation that needs review): pages/deployment/argo.md
          - AWS Batch (outdated documentation that needs review): pages/deployment/aws_batch.md
      - CONTRIBUTE TO KEDRO:
          - Contribution Guide: pages/contribution/index.md
      - CLI REFERENCE:
          - Commands Reference: pages/development/commands_reference.md
      - API DOCUMENTATION:
          - kedro.config: api/kedro.config.md
          - kedro.framework:
              - Overview: api/framework/kedro.framework.md
              - CLI: api/framework/kedro.framework.cli.md
              - Context: api/framework/kedro.framework.context.md
              - Hooks: api/framework/kedro.framework.hooks.md
              - Project: api/framework/kedro.framework.project.md
              - Session: api/framework/kedro.framework.session.md
              - Startup: api/framework/kedro.framework.startup.md
          - kedro.io:
              - Overview: api/io/kedro.io.md
              - AbstractDataset: api/io/kedro.io.AbstractDataset.md
              - AbstractVersionedDataset: api/io/kedro.io.AbstractVersionedDataset.md
              - CachedDataset: api/io/kedro.io.CachedDataset.md
              - DataCatalog: api/io/kedro.io.DataCatalog.md
              - LambdaDataset: api/io/kedro.io.LambdaDataset.md
              - MemoryDataset: api/io/kedro.io.MemoryDataset.md
              - Version: api/io/kedro.io.Version.md
              - DatasetAlreadyExistsError: api/io/kedro.io.DatasetAlreadyExistsError.md
              - DatasetError: api/io/kedro.io.DatasetError.md
              - DatasetNotFoundError: api/io/kedro.io.DatasetNotFoundError.md
          - kedro.logging: api/kedro.logging.md
          - kedro.pipeline:
              - Overview: api/pipeline/kedro.pipeline.md
              - node: api/pipeline/kedro.pipeline.node.md
              - modular_pipeline.pipeline: api/pipeline/kedro.pipeline.modular_pipeline.pipeline.md
              - Pipeline: api/pipeline/kedro.pipeline.Pipeline.md
              - Node: api/pipeline/kedro.pipeline.node.Node.md
              - ModularPipelineError: api/pipeline/kedro.pipeline.modular_pipeline.ModularPipelineError.md
          - kedro.runner:
              - Overview: api/runner/kedro.runner.md
              - run_node: api/runner/kedro.runner.run_node.md
              - AbstractRunner: api/runner/kedro.runner.AbstractRunner.md
              - SequentialRunner: api/runner/kedro.runner.SequentialRunner.md
              - ParallelRunner: api/runner/kedro.runner.ParallelRunner.md
              - ThreadRunner: api/runner/kedro.runner.ThreadRunner.md
          - kedro.utils: api/kedro.utils.md
  - Kedro-Viz: readthedocs.io/projects/kedro-viz
  - Kedro-Datasets: https://docs.kedro.org/projects/kedro-datasets

