name: Detect secrets on Kedro

on:
  push:
    branches: ['*']  # Runs on any push to any branch
  pull_request:
    branches: ['*']  # Also runs on any pull request

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache python packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ubuntu-latest-python-3.10

      - name: Install dependencies
        run: |
          make install-test-requirements
          make install-pre-commit

      - name: pip freeze
        run: uv pip freeze --system

      - name: Scan all tracked files
        run: git ls-files -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline
